### ISSUE TITLE
ENOENT error : dart is on my PATH and still errors

### ISSUE THREAD

**Issue by nektro** [agudulin/gulp-dart#15]
I installed the Dart SDK and added it to my path, can compile pages manually, but still receive the ENOENT error when using gulp.

```
PS C:\Users\nektr\Desktop\nektro.net> gulp
[22:07:31] Using gulpfile ~\Desktop\nektro.net\gulpfile.js
[22:07:31] Starting 'html'...
[22:07:31] Starting 'static-2'...
[22:07:31] Starting 'dart'...
[22:07:31] Starting 'static'...
events.js:165
      throw er; // Unhandled 'error' event
      ^
Error: spawn dart2js ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:178:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:207:12)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:178:19)
PS C:\Users\nektr\Desktop\nektro.net> dart2js
Usage: dart2js [options] dartfile
Compiles Dart to JavaScript.
Common options:
  -o <file> Generate the output into <file>.
  -c        Insert runtime type checks and enable assertions (checked mode).
  -m        Generate minified output.
  -h        Display this message (add -v for information about all options).
Error: No Dart file specified.
PS C:\Users\nektr\Desktop\nektro.net>
```

I looked up other common causes of the ENOENT error and most say it's due to a `clean` task or similar but I do not have such a task that deletes any folders.

**Comment by nektro** [comment]
My `dart` task:
```js
gulp.task("dart", function() {
    return gulp.src("src/**/*.dart")
    .pipe(dart({ dest:"bin", minify:true }))
    .pipe(gulp.dest("bin"));
});
```
